export const appRoutes = {
  home: "/",
  login: "/auth/login",
  app: "/app",
  dashboard: "/app",
  quotations: "/app/quotations",
  quotationBuilder: (id: string) => `/app/quotations/${id}`,
  products: "/app/products",
  customers: "/app/customers",
  governance: "/app/governance",
  approvals: "/app/approvals",
  approvalDetail: (id: string) => `/app/approvals/${id}`,
  fulfillment: "/app/fulfillment",
  billing: "/app/billing",
  dealHealth: "/app/deal-health",
  reports: "/app/reports",
  settings: "/app/settings",
} as const;
